services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: strava_user
      POSTGRES_PASSWORD: strava_password
      POSTGRES_DB: strava_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strava_network

volumes:
  postgres_data:

networks:
  strava_network:
    driver: bridge
